steps:
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.' ]
  # Push the conatiner image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/gcpdevops']
  # Deploy the container image to gke 
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
    - run
    - --filename=gke.yaml
    - --image=gcr.io/$PROJECT_ID/gcpdevops
    - --location=us-west1-a
    - --cluster=gcp-devops-k8
    - --namespace=gcp-devops-prod
