apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gcp-devops-deploy
  name: gcp-devops-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: gcp-devops-deploy
  template:
    metadata:
      labels:
        app: gcp-devops-deploy
    spec:
      containers:
      - image: gcr.io/first-server-384515/gcpdevops-dev:latest 
        name: gcpdevops
        ports:
          - containerPort: 5000
        env:
          - name: PORT
            value: "5000"
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gcp-devops-deploy
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
  name: gcp-devops-svc
  namespace: gcp-devops-dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: gcp-devops-deploy
  type: "LoadBalancer"
