apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gcp-devops-deploy
  name: gcp-devops-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-devops-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: gcp-devops-deploy
    spec:
      containers:
      - image: gcr.io/$PROJECT_ID/gcpdevops:latest
        name: gcpdevops
        ports:
          - containerPort: 5000
        env:
          - name: PORT
            value: "5000"